metrics:
  location:
    queue: src/main/resources/metrics/queue_metrics.csv
application:
  execution:
    count-client-emitted:
    count-client-processed:
    time-seconds:
model:
  parameter:
    mu: 3
    lambda: 10
    queue-depth: 2